version: '3'
services:
  rabbitmq:
    build: ./
    restart: always
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/lib:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 1883:1883
      - 61613:61613
      - 25672:25672
      - 15672:15672
      - 15674:15674
      - 15675:15675