version: '3'
services:
  nginx:
    build: ./
    restart: always
    volumes:
      - ./nginx/vhost:/etc/nginx/vhost
      - ./nginx/log:/var/log/nginx
      - ./website:/website
    ports:
      - 80:80
      - 443:443